- src: siamaksade.openshift_sonatype_nexus
  version: 1.1.0
  name: openshift_sonatype_nexus

- src: siamaksade.openshift_gogs
  version: 1.1.0
  name: openshift_gogs

- src: siamaksade.openshift_workshopper
  version: 1.2.0
  name: openshift_workshopper

- src: siamaksade.openshift_eclipse_che
  version: 1.2.0
  name: openshift_eclipse_che

- src: siamaksade.openshift_jenkins
  version: 1.3.0
  name: openshift_jenkins
